INSERT INTO ECOMMERCE.CATEGORIE(NOM) VALUES('Indie-Pop');
INSERT INTO ECOMMERCE.CATEGORIE(NOM) VALUES('Alternatif');
INSERT INTO ECOMMERCE.CATEGORIE(NOM) VALUES('Pop-Rock');
INSERT INTO ECOMMERCE.CATEGORIE(NOM) VALUES('Punk-Rock');

INSERT INTO ECOMMERCE.ARTICLE(NOM,DESCRIPTION,PRIX,QUANTITE,URL_IMAGE,DATE_CREATION,ID_CATEGORIE) VALUES ("You are here","Premier album de Magic Man, groupe Indie-Pop pour les fans The Killers, THe Naked Famous","10","100","img/magicman.png","20 Mars 2014", 1);