INSERT INTO ECOMMERCE.CATEGORIE(NOM) VALUES('Indie-Pop');
INSERT INTO ECOMMERCE.CATEGORIE(NOM) VALUES('Alternatif');
INSERT INTO ECOMMERCE.CATEGORIE(NOM) VALUES('Pop-Rock');
INSERT INTO ECOMMERCE.CATEGORIE(NOM) VALUES('Punk-Rock');

INSERT INTO ECOMMERCE.ARTICLE(NOM,DESCRIPTION,PRIX,QUANTITE,URL_IMAGE,DATE_CREATION,ID_CATEGORIE) VALUES ('You are here','Premier album de Magic Man','10','100','img/magicman.jpg','20 Mars 2014', 1);
INSERT INTO ECOMMERCE.ARTICLE(NOM,DESCRIPTION,PRIX,QUANTITE,URL_IMAGE,DATE_CREATION,ID_CATEGORIE) VALUES ('Lido','Album de The Colourist','10','100','img/lido.png','20 Mars 2014', 1);
INSERT INTO ECOMMERCE.ARTICLE(NOM,DESCRIPTION,PRIX,QUANTITE,URL_IMAGE,DATE_CREATION,ID_CATEGORIE) VALUES ('Hunter Hunted','Hunter Hunted','10','100','img/hunterhunted.png','20 Mars 2014', 1);
INSERT INTO ECOMMERCE.ARTICLE(NOM,DESCRIPTION,PRIX,QUANTITE,URL_IMAGE,DATE_CREATION,ID_CATEGORIE) VALUES ('Waiting For The Dawn','The Mowglis','10','100','img/mowglis.jpg','20 Mars 2014', 1);
INSERT INTO ECOMMERCE.ARTICLE(NOM,DESCRIPTION,PRIX,QUANTITE,URL_IMAGE,DATE_CREATION,ID_CATEGORIE) VALUES ('Signs and Wonders','Animal Kingdom','10','100','img/signs.jpg','20 Mars 2014', 1);
INSERT INTO ECOMMERCE.ARTICLE(NOM,DESCRIPTION,PRIX,QUANTITE,URL_IMAGE,DATE_CREATION,ID_CATEGORIE) VALUES ('Sand & Snow','A Silent Film','10','100','img/asilentfilm.jpg','20 Mars 2014', 1);
INSERT INTO ECOMMERCE.ARTICLE(NOM,DESCRIPTION,PRIX,QUANTITE,URL_IMAGE,DATE_CREATION,ID_CATEGORIE) VALUES ('Youngblood Hawke','Youngblood Hawke','20','100','img/yh.jpg','20 Mars 2014', 2);