CREATE TABLE ECOMMERCE.ARTICLE
(ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
NOM VARCHAR(100) NOT NULL,
DESCRIPTION DECIMAL(10,2),
PRIX VARCHAR(25),
QUANTITE VARCHAR(25),
URL_IMAGE VARCHAR(25),
DATE_CREATION DATE,
PRIMARY KEY (ID)) ;

CREATE TABLE ECOMMERCE.CLIENT
(ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
NOM VARCHAR(100) NOT NULL,
PRENOM VARCHAR(100) NOT NULL,
TELEPHONE VARCHAR(100),
ADRESSE VARCHAR(100),
CODE_POSTAL VARCHAR(100),
VILLE VARCHAR(100),
DATE_CREATION DATE,
PRIMARY KEY (ID)) ;

CREATE TABLE ECOMMERCE.CATEGORIE
(ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
NOM VARCHAR(100) NOT NULL,
PRIMARY KEY (ID)) ;

CREATE TABLE ECOMMERCE.COMMANDE
(ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
ID_CLIENT VARCHAR(100) NOT NULL,
ID_ARTICLE VARCHAR(100) NOT NULL,
PRIMARY KEY (ID)) ;